Lab_PPW_V2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from pptwebreborn.views import index as index

urlpatterns = [
    url('admin/', admin.site.urls),
    url('pptwebreborn/', include(('pptwebreborn.urls', 'pptwebreborn'), namespace='pptwebreborn')),
    url('', index, name='home'),
]

pptwebreborn/urls.py
from django.urls import path
from .views import index, savedStatus, profile

urlpatterns = [
	path('', index, name='home'),
	path('savedStatus/', savedStatus, name='savedStatus'),
	path('profile/', profile, name='profile'),
]

pptwebreborn/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=300)
    created_at = models.DateTimeField(default=timezone.now)

pptwebreborn/forms.py
from django import forms

class Status_Form(forms.Form):
    attrs = {'class': 'form-control'}
    status = forms.CharField(label='Status:', required=True, max_length=300, widget=forms.TextInput(attrs=attrs))

pptwebreborn/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

response = {}
question = "Hello, Apa kabar?"

# Create your views here.
def index(request):
    response['question'] = question
    response['status_form'] = Status_Form
    allStatus = Status.objects.all().values()
    response['allStatus'] = allStatus
    return render(request, 'pptwebreborn.html', response)

def profile(request):
    return render(request, 'profile.html', response)

def savedStatus(request):
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status=response['status'])
        status.save()
        allStatus = Status.objects.all().values()
        response['allStatus'] = allStatus
        return render(request, 'pptwebreborn.html', response)
    else:
        return HttpResponseRedirect('/pptwebreborn/')

pptwebreborn/templates/pptwebreborn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
      <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Hello</title>
</head>
<body>

    <h1> {{ question }} </h1>
    <br>

     <form id="form" method="POST" action="{% url 'pptwebreborn:savedStatus' %}">
         {% csrf_token %}
         {{ status_form }}
         <button type="submit" class="btn btn-default">Submit</button>
     </form>
    <br>

    <table id="status_table">
        <thead>
            <th>Status</th>
            <th>Created Date</th>
        </thead>
    <tbody>
        {% for i in allStatus %}
        <tr class="success">
            <td> {{i.status}} </td>
            <td> {{i.created_at}} </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

</body>
</html>

pptwebreborn/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Title</title>
</head>
<body>

    <!--profile start -->
		<section id="profile" class="profile">
            <div class="section-heading text-center">
                <h2>PROFILE</h2>
                <img src="{% static 'images/photo.gif' %}" alt="Nabila Febri Viola" img id="profile-photo">
                <h3>Nabila Febri Viola</h3>
                <p id="description-bio">
                    I was born on the 3rd of February 1999 in Jakarta.
                    I am currently living in Depok to pursue my dream of becoming a programmer.
                    I spend my time by playing games, reading books, watching movies, writing reviews, and solving jigsaw puzzles.
                </p>
            </div>
        </section>
</body>
</html>